spin_manifest_version = 2

[application]
name = "mdn-aoc2023-c1"
version = "0.1.0"
authors = ["Marco De Nittis <marco.denittis@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "mdn-aoc2023-c1"

[component.mdn-aoc2023-c1]
source = "target/wasm32-wasi/release/mdn_aoc2023_c1.wasm"
allowed_outbound_hosts = []
[component.mdn-aoc2023-c1.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]


