spin_manifest_version = 2

[application]
name = "mdn-aoc2023-c1"
version = "0.1.0"
authors = ["Marco De Nittis <marco.denittis@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "mdn-aoc2023-c1"

[component.mdn-aoc2023-c1]
source = "target/wasm32-wasi/release/mdn_aoc2023_c1.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.mdn-aoc2023-c1.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]


[[trigger.http]]
route = "/index.html"
component = "static-index"

[component.static-index]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "assets", destination = "/" }]

